<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HobbiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $hobbies = [
            ['name' => 'Reading'],
            ['name' => 'Cooking'],
            ['name' => 'Hiking'],
            ['name' => '3D printing'],		
		    ['name' => 'Amateur radio'],		
		    ['name' => 'Scrapbook'],		
		    ['name' => 'Acting'],		
		    ['name' => 'Baton twirling'],		
		    ['name' => 'Board games'],		
		    ['name' => 'Book restoration'],		
		    ['name' => 'Cabaret'],		
		    ['name' => 'Calligraphy'],		
		    ['name' => 'Candle making'],		
		    ['name' => 'Computer programming'],		
		    ['name' => 'Coffee roasting'],		
		    ['name' => 'Colouring'],		
		    ['name' => 'Cosplaying'],		
		    ['name' => 'Couponing'],		
		    ['name' => 'Creative writing'],		
		    ['name' => 'Crocheting'],		
		    ['name' => 'Cryptography'],		
		    ['name' => 'Dance'],		
		    ['name' => 'Digital arts'],		
		    ['name' => 'Drama'],		
		    ['name' => 'Drawing'],		
		    ['name' => 'Do it yourself'],		
		    ['name' => 'Electronics'],		
		    ['name' => 'Embroidery'],		
		    ['name' => 'Fashion'],		
		    ['name' => 'Flower arranging'],		
		    ['name' => 'Foreign language learning'],		
		    ['name' => 'Gaming'],		
		    ['name' => 'Tabletop games'],		
		    ['name' => 'Role-playing games'],		
		    ['name' => 'Gambling'],		
		    ['name' => 'Genealogy'],		
		    ['name' => 'Glassblowing'],		
		    ['name' => 'Gunsmithing'],		
		    ['name' => 'Homebrewing'],		
		    ['name' => 'Ice skating'],		
		    ['name' => 'Jewelry making'],		
		    ['name' => 'Jigsaw puzzles'],		
		    ['name' => 'Juggling'],		
		    ['name' => 'Knapping'],		
		    ['name' => 'Knitting'],		
		    ['name' => 'Kabaddi'],		
		    ['name' => 'Knife making'],		
		    ['name' => 'Lacemaking'],		
		    ['name' => 'Lapidary'],		
		    ['name' => 'Leather crafting'],		
		    ['name' => 'Lego building'],		
		    ['name' => 'Lockpicking'],		
		    ['name' => 'Machining'],		
		    ['name' => 'Macrame'],		
		    ['name' => 'Metalworking'],		
		    ['name' => 'Magic'],		
		    ['name' => 'Model building'],		
		    ['name' => 'Listening to music'],		
		    ['name' => 'Origami'],		
		    ['name' => 'Painting'],		
		    ['name' => 'Playing musical instruments'],		
		    ['name' => 'Pet'],		
		    ['name' => 'Poi'],		
		    ['name' => 'Pottery'],		
		    ['name' => 'Puzzles'],		
		    ['name' => 'Quilting'],		
		    ['name' => 'Reading'],		
		    ['name' => 'Scrapbooking'],		
		    ['name' => 'Sculpting'],		
		    ['name' => 'Sewing'],		
		    ['name' => 'Singing'],		
		    ['name' => 'Sketching'],		
		    ['name' => 'Soapmaking'],		
		    ['name' => 'Sports'],		
		    ['name' => 'Stand-up comedy'],		
		    ['name' => 'Sudoku'],		
		    ['name' => 'Table tennis'],		
		    ['name' => 'Taxidermy'],		
		    ['name' => 'Video gaming'],		
		    ['name' => 'Watching movies'],		
		    ['name' => 'Web surfing'],		
		    ['name' => 'Whittling'],		
		    ['name' => 'Wood carving'],		
		    ['name' => 'Woodworking'],		
		    ['name' => 'World Building'],		
		    ['name' => 'Writing'],		
		    ['name' => 'Yoga'],		
		    ['name' => 'Yo-yoing'],		
		    ['name' => 'Air sports'],		
		    ['name' => 'Archery'],		
		    ['name' => 'Astronomy'],		
		    ['name' => 'Backpacking'],		
		    ['name' => 'Base jumping'],		
		    ['name' => 'Baseball'],		
		    ['name' => 'Basketball'],		
		    ['name' => 'Beekeeping'],		
		    ['name' => 'Bird watching'],		
		    ['name' => 'Blacksmithing'],		
		    ['name' => 'Board sports'],		
		    ['name' => 'Bodybuilding'],		
		    ['name' => 'Brazilian jiu-jitsu'],		
		    ['name' => 'Community'],		
		    ['name' => 'Cycling'],		
		    ['name' => 'Dowsing'],		
		    ['name' => 'Driving'],		
		    ['name' => 'Fishing'],		
		    ['name' => 'Flag football'],		
		    ['name' => 'Flying'],		
		    ['name' => 'Flying disc'],		
		    ['name' => 'Foraging'],		
		    ['name' => 'Gardening'],		
		    ['name' => 'Geocaching'],		
		    ['name' => 'Ghost hunting'],		
		    ['name' => 'Graffiti'],		
		    ['name' => 'Handball'],		
		    ['name' => 'Hiking'],		
		    ['name' => 'Hooping'],		
		    ['name' => 'Horseback riding'],		
		    ['name' => 'Hunting'],		
		    ['name' => 'Inline skating'],		
		    ['name' => 'Jogging'],		
		    ['name' => 'Kayaking'],		
		    ['name' => 'Kite flying'],		
		    ['name' => 'Kitesurfing'],		
		    ['name' => 'Larping'],		
		    ['name' => 'Letterboxing'],		
		    ['name' => 'Metal detecting'],		
		    ['name' => 'Motor sports'],		
		    ['name' => 'Mountain biking'],		
		    ['name' => 'Mountaineering'],		
		    ['name' => 'Mushroom hunting'],		
		    ['name' => 'Mycology'],		
		    ['name' => 'Netball'],		
		    ['name' => 'Nordic skating'],		
		    ['name' => 'Orienteering'],		
		    ['name' => 'Paintball'],		
		    ['name' => 'Parkour'],		
		    ['name' => 'Photography'],		
		    ['name' => 'Polo'],		
		    ['name' => 'Rafting'],		
		    ['name' => 'Rappelling'],		
		    ['name' => 'Rock climbing'],		
		    ['name' => 'Roller skating'],		
		    ['name' => 'Rugby'],		
		    ['name' => 'Running'],		
		    ['name' => 'Sailing'],		
		    ['name' => 'Sand art'],		
		    ['name' => 'Scouting'],		
		    ['name' => 'Scuba diving'],		
		    ['name' => 'Sculling'],		
		    ['name' => 'Rowing'],		
		    ['name' => 'Shooting'],		
		    ['name' => 'Shopping'],		
		    ['name' => 'Skateboarding'],		
		    ['name' => 'Skiing'],		
		    ['name' => 'Skim Boarding'],		
		    ['name' => 'Skydiving'],		
		    ['name' => 'Slacklining'],		
		    ['name' => 'Snowboarding'],		
		    ['name' => 'Stone skipping'],		
		    ['name' => 'Surfing'],		
		    ['name' => 'Swimming'],		
		    ['name' => 'Taekwondo'],		
		    ['name' => 'Tai chi'],		
		    ['name' => 'Urban exploration'],		
		    ['name' => 'Vacation'],		
		    ['name' => 'Vehicle restoration'],		
		    ['name' => 'Water sports'],
		// Add more hobbies as needed
        ];
        // Extract the 'name' values from the array
		$hobbyNames = array_column($hobbies, 'name');
		// Remove duplicates and preserve the keys
		$uniqueHobbyNames = array_unique($hobbyNames);
		// Rebuild the hobbies array with unique 'name' values
		$uniqueHobbies = [];
		foreach ($uniqueHobbyNames as $name) {
		    $uniqueHobbies[] = ['name' => $name];
		}

        DB::table('hobbies')->insert($uniqueHobbies);
    }
}
